---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Enable SSH service
  systemd:
    name: ssh
    enabled: true
    state: started